on:
  - push

jobs:

  test:
    name: Build, test, check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.2'
          elixir-version: '1.12'
      - run: mix deps.get
      - run: mix compile
      - run: docker run --detach --publish 6363:6363 terminusdb/terminusdb-server:dev
      - run: mix test
      - run: mix format --check-formatted
