name: Test
on:
  pull_request:
  push:
    branches:
      - main
env:
  OTP_VERSION: "25.0"
  ELIXIR_VERSION: "1.14.0"
  MIX_ENV: test
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          elixir-version: "${{ env.ELIXIR_VERSION }}"
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            cache
          key: ${{ runner.os }}-mix-${{ matrix.pair.elixir }}-${{ matrix.pair.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install mix dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run tests
        run: mix test